services:
  backend:
    build: .
    command: python core/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A core.celery.app worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - backend
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A core.celery.app beat --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - backend
      - redis
    env_file:
      - .env

volumes:
  mongo_data:
  redis_data: